#!/bin/sh
#
#    This file is part of the RMAP software
#
#    Copyright (C) 2008 Cold Spring Harbor Laboratory, 
#                       University of Southern California and
#                       Andrew D. Smith
#
#    Authors: Andrew D. Smith
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#


TEST_CHROM=$1/input/chr8.fa

./simreadsbs -S 1 -o test_reads_bs.fa -n 100 -w 36 -e 2 ${TEST_CHROM}
./simreadsbs -S 1 -p test_reads_bs.prb -o test_reads_bs.fa -n 100 -w 36 -e 2 ${TEST_CHROM}
./simreadsbs -S 1 -q -o test_reads_bs.fq -n 100 -w 36 -e 2 ${TEST_CHROM}

if [ "`diff --brief test_reads_bs.fa $1/output`" = "" ] && \
    [ "`diff --brief test_reads_bs.fa $1/output`" = "" ] && \
    [ "`diff --brief test_reads_bs.prb $1/output`" = "" ]; then
    echo "PASS"
else
    echo "FAIL" 
fi
rm test_reads_bs.fa test_reads_bs.fq test_reads_bs.prb
