#!/bin/sh
#
#    This file is part of the RMAP software
#
#    Copyright (C) 2008 Cold Spring Harbor Laboratory, 
#                       University of Southern California and
#                       Andrew D. Smith
#
#    Authors: Andrew D. Smith
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#


TEST_CHROM=$1/input/chr8.fa
TEST_READS=$1/input/test_reads_bs.fa
TEST_READS_FQ=$1/input/test_reads_bs.fq
TEST_PRB=$1/input/test_reads_bs.prb

./rmapbs -o test_reads_bs.bed -a test_reads_bs.amb -c  ${TEST_CHROM} ${TEST_READS}
./rmapbs -o test_reads_bs_fq.bed -a test_reads_bs_fq.amb -c  ${TEST_CHROM} ${TEST_READS_FQ}
./rmapbs -o test_reads_bs_prb.bed -a test_reads_bs_prb.amb -c  ${TEST_CHROM} -p ${TEST_PRB} ${TEST_READS}

if [ "`diff --brief test_reads_bs.bed $1/output`" = "" ] && \
    [ "`diff --brief test_reads_bs.amb $1/output`" = "" ] && \
    [ "`diff --brief test_reads_bs_fq.bed $1/output`" = "" ] && \
    [ "`diff --brief test_reads_bs_fq.amb $1/output`" = "" ] && \
    [ "`diff --brief test_reads_bs_prb.bed $1/output`" = "" ] && \
    [ "`diff --brief test_reads_bs_prb.amb $1/output`" = "" ]; then
    echo "PASS"
else
    echo "FAIL"
fi
rm test_reads_bs.bed test_reads_bs.amb test_reads_bs_fq.bed test_reads_bs_fq.amb test_reads_bs_prb.bed test_reads_bs_prb.amb
