#!/bin/sh
#
#    This file is part of the RMAP software
#
#    Copyright (C) 2008 Cold Spring Harbor Laboratory, 
#                       University of Southern California and
#                       Andrew D. Smith
#
#    Authors: Andrew D. Smith
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#


TEST_CHROM=$1/input/chr8.fa
TEST_READS=$1/input/test_reads.fa
TEST_READS_Q=$1/input/test_reads_q.fa
TEST_PRB=$1/input/test_reads_q.prb

./rmap -o test_reads.bed -a test_reads.amb -S 3 -h 10 -m 2 -w 32 -c ${TEST_CHROM} ${TEST_READS}
./rmap -o test_reads_q.bed -c ${TEST_CHROM} -S 3 -h 9 -w 35 -m 2 -a test_reads_q.amb -p ${TEST_PRB} ${TEST_READS_Q}

if [ `diff --brief test_reads.bed $1/output`="" ] && \
   [ `diff --brief test_reads.amb $1/output`="" ]; then
	echo "PASS"
fi
rm test_reads.bed test_reads.amb
