#!/bin/sh
#
#    This file is part of the RMAP software
#
#    Copyright (C) 2008 Cold Spring Harbor Laboratory, 
#                       University of Southern California and
#                       Andrew D. Smith
#
#    Authors: Andrew D. Smith
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#


TEST_CHROM=$1/input/chr8.fa

./simreadsbs -o test_reads_bs.fa -n 1000 -w 35 -e 2 -S 1 ${TEST_CHROM}
if [ "`diff --brief test_reads_bs.fa $1/output`" = "" ]; then
        echo "PASS"
else
	echo "FAIL" 
fi
rm test_reads_bs.fa
